services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
       - 54:54

  redis:
    image: redis:alpine
    security_opt: 
       - no-new-privileges=true
    read_only: true

  sqli:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
       - postgres
       - redis
    ports:
       - 80:80
    command: | 
      wait-for postgres:54 -- python run.py
